<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Salsa Nabilla">
<meta name="dcterms.date" content="2024-01-10">

<title>Pengaruh Ekspor Minyak Kelapa Sawit terhadap PDB di Indonesia Periode 2013-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor Minyak Kelapa Sawit terhadap PDB di Indonesia Periode 2013-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Salsa Nabilla </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 10, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid" width="236"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Penelitian ini dimulai dengan menggambarkan pentingnya sektor minyak kelapa sawit dalam ekonomi Indonesia selama periode 2013-2022. Pertumbuhan ekspor minyak kelapa sawit telah menjadi salah satu pendorong utama pertumbuhan ekonomi negara ini. Selain itu, penelitian ini bertujuan untuk menganalisis dampak ekspor minyak kelapa sawit terhadap Produk Domestik Bruto (PDB) Indonesia selama periode tersebut.</p>
<p>Alasan pemilihan periode 2013-2022 adalah untuk dapat mengamati tren dan pola dalam ketergantungan ekonomi Indonesia terhadap ekspor minyak kelapa sawit dalam rentang waktu yang cukup panjang. Data yang komprehensif selama periode ini akan memberikan pemahaman mengenai pengaruh ekspor minyak kelapa sawit terhadap pertumbuhan ekonomi dan kontribusinya terhadap PDB.</p>
<p>Dalam konteks ini, penelitian ini bertujuan untuk menilai apakah ekspor minyak kelapa sawit masih memegang peran penting dalam pertumbuhan ekonomi di Indonesia serta dapat menjadi sumber pendapatan yang signifikan.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Pada penelitian ini penulis mengambil objek penelitian dari UN Comtrade Database dan World Development Indicators. Ruang lingkup penelitian ini yaitu Nilai ekspor minyak kelapa sawit dari Indonesia serta Nilai Produk Domestik Bruto (PDB) Indonesia dengan menggunakan data yang bersifat time series yaitu dalam kurun waktu 2013-2022. Satuan pada data ini telah diubah ke dalam USD untuk memudahkan penyetaraan mata uang secara internasional, dan dengan batasan ruang lingkup ini dapat membantu mengidentifikasi masalah yang akan dibahas.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan latar belakang yang telah diuraikan, maka rumusan masalah yang digunakan sebagai berikut:</p>
<ol type="1">
<li><p>Apakah ekspor minyak kelapa sawit mempegaruhi PDB di Indonesia selama periode 2013-2022?</p></li>
<li><p>Apakah terdapat hubungan antara jumlah ekspor minyak kelapa sawit dengan pertumbuhan ekonomi?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan dari penelitian ini adalah untuk menilai bagaimana ekspor minyak kelapa sawit memengaruhi Pertumbuhan Domestik Bruto (PDB) Indonesia selama periode 2013-2022. Selain itu, untuk mengidentifikasi apakah terdapat hubungan yang signifikan antara jumlah ekspor minyak kelapa sawit terhadap pertubuhan ekonomi Indonesia.</p>
<p>Manfaat penelitian, antara lain:</p>
<ol type="1">
<li><p>Bagi Pembaca Memberikan wawasan tentang pentingnya dan dampak ekspor minyak kelapa sawit terhadap pertumbuhan ekonomi nasional.</p></li>
<li><p>Bagi Industri Memberikan informasi yang berguna bagi para pelaku industry minyak kelapa sawit untuk memahami hubungan antara ekspor dan pertumbuhan ekonomi.</p></li>
</ol>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan pada penelitian ini antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Indonesia sebagai negara produsen pertama yang mengekspor minyak sawit (Syamsulbahri, 1996). meskipun kini posisinya telah tergeser oleh Malaysia, namun Indonesia masih berhasil mempertahankan suplai minyak sawit hingga saat ini.</p>
<p>Minyak kelapa sawit merupakan salah satu jenis minyak yang paling banyak dikonsumsi dan diproduksi di seluruh dunia.Karena minyak kelapa sawit terjangkau, mudah diproduksi, dan sangat stabil, minyak ini dapat digunakan untuk berbagai jenis makanan, kosmetik, dan produk perawatan pribadi. Minyak ini juga dapat digunakan sebagai pengganti biofuel atau biodiesel. Banyak pabrik pengolahan kelapa sawit kecil diproduksi di Asia, Afrika, dan Amerika Utara karena pabrik-pabrik kecil tersebut membutuhkan kelembaban tinggi, suhu rendah, dan panjang pemotongan yang pendek untuk memaksimalkan produksinya.</p>
<p>Indonesia adalah salah satu produsen kelapa sawit terbesar di dunia, dengan total luas area mencapai 16,38 juta hektar dan produksi CPO sebesar 46,8 juta ton. Dari berbagai jenis kelapa sawit, kelapa sawit kelapa adalah produk yang paling dikenal oleh masyarakat umum.</p>
<p>Dalam konteks ekonomi, kelapa sawit telah berperan sebagai kontributor utama dalam ekonomi negara di masing-masing dari 38 provinsi dan kota di Indonesia. Banyak pulau dan kota yang terdampak oleh kelapa sawit, terutama di Provinsi Riau dan pulau lainnya di Kalimantan dan Sulawesi.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut data yang digunakan dalam penelitian dalam satuan USD:</p>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>ekspor (X)</th>
<th>PDB (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>15.838.850.170</td>
<td>9.125241e+11</td>
</tr>
<tr class="even">
<td>2014</td>
<td>17.464.904.662</td>
<td>8.908148e+11</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>15.385.275.322</td>
<td>8.608542e+11</td>
</tr>
<tr class="even">
<td>2016</td>
<td>14.365.422.161</td>
<td>9.318774e+11</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>18.513.462.522</td>
<td>1.015619e+12</td>
</tr>
<tr class="even">
<td>2018</td>
<td>16.527.848.105</td>
<td>1.042272e+12</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>14.716.274.696</td>
<td>1.119100e+12</td>
</tr>
<tr class="even">
<td>2020</td>
<td>17.363.920.824</td>
<td>1.059055e+12</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>26.665.127.850</td>
<td>1.186505e+12</td>
</tr>
<tr class="even">
<td>2022</td>
<td>27.765.830.185</td>
<td>1.319100e+12</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data time series 2013-2022, data yang digunakan adalah data yang telah diolah oleh UN Comtrade Database.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'D:/Metodologi Penelitian/Tugas UAS'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'latihan.xlsx'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>dat,Y<span class="sc">~</span>X)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"ekspor minyak kelapa sawit"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot Pengaruh Error terhadap ekspor minyak kelapa sawit</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>Y,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"pdb"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot Pengaruh Error terhadap PDB di Indonesia</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini merbaksud mencari hubungan antara PDB Indonesia dan Nilai ekspor minyak kelapa sawit. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah PDB Indonesia dan <span class="math inline">\(x_t\)</span> adalah Nilai ekspor minyak kelapa sawit.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Variabel</th>
<th>Estimate Std.</th>
<th>Error</th>
<th>t value</th>
<th>Prob (.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>5.920e+11</td>
<td>1.236e+11</td>
<td>4.790</td>
<td>0.00137</td>
</tr>
<tr class="even">
<td>X</td>
<td>2.393e+01</td>
<td>6.500e+00</td>
<td>3.682</td>
<td>0.00620</td>
</tr>
<tr class="odd">
<td>R Squared</td>
<td>0.6289</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Adjusted R Squared</td>
<td>0.5825</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>F-statistic</td>
<td>13.56</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Prob(F-statistic)</td>
<td>0.006203</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Hasil regresi setelah dimasukan ke dalam rumus persamaan adalah:</p>
<p><span class="math display">\[
Y=5.290 +  2.393X
\]</span></p>
<p>Ekspor memainkan peran penting dalam meningkatkan Pertumbuhan Domestik Bruto (PDB) melalui dampak positif variabel X, namun analisis regresi menunjukkan bahwa pengaruh ekspor terhadap PDB Indonesia tidak bersifat mutlak. Artinya, peningkatan PDB tidak hanya disebabkan oleh ekspor semata, melainkan dipengaruhi oleh faktor-faktor lain. Dapat diasumsikan bahwa setiap kenaikan nilai ekspor sebesar 1 maka terjadi peningkatan PDB sebesar 5.920.</p>
<p>Adjusted R-squared sebesar 0.5825 mengindikasikan bahwa variabel independen dalam penelitian ini dapat menjelaskan sekitar 58,25% variasi variabel dependen. F-statistik dengan nilai 13.56 mengimplikasikan bahwa variabel independen, seperti ekspor, memiliki pengaruh signifikan terhadap pertumbuhan ekonomi atau PDB di Indonesia dalam jangka panjang.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'D:/Metodologi Penelitian/Tugas UAS'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'latihan.xlsx'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>dat,Y<span class="sc">~</span>X)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = dat)

Residuals:
       Min         1Q     Median         3Q        Max 
-1.191e+11 -5.478e+10 -1.165e+10  5.395e+10  1.749e+11 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 5.920e+11  1.236e+11   4.790  0.00137 **
X           2.393e+01  6.500e+00   3.682  0.00620 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.351e+10 on 8 degrees of freedom
Multiple R-squared:  0.6289,    Adjusted R-squared:  0.5825 
F-statistic: 13.56 on 1 and 8 DF,  p-value: 0.006203</code></pre>
</div>
</div>
<p>Dapat dilihat dari tabel diatas bahwa setiap kenaikan nilai ekspor minyak kelapa sawit sebesar 1, maka terjadi peningkatan pertumbuhan ekonomi atau PDB sebesar 5.920 di Indonesia.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Setelah dilakukan penelitian melalui sistem regresi univariat, maka dapat disimpulkan bahwa:</p>
<ol type="1">
<li><p>Ekspor minyak kelapa sawit mempengaruhi terhadap PDB di Indonesia pada periode 2013-2022, namun hal ini bukan merupakan faktor utama yang mempengaruhi PDB Indonesia karena terdapat faktor lainnya juga yang menunjang peningkatan PDB di Indonesia.</p></li>
<li><p>Hubungan antara jumlah ekspor kelapa sawit dengan PDB Indonesia dapat dilihat dari nilai ekspor minyak kelapa sawit yang memiliki nilai positif sehingga apabila jumlah minyak kelapa sawit yang diekspor ke luar negeri semakin banyak maka arus modal yang masuk ke dalam negeri juga dalam jumlah yang banyak.</p></li>
</ol>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Abidin, Z. (2008). Analisis Ekspor Minyak Kelapa Sawit (Cpo) Indonesia. In Jurnal Aplikasi Manajemen (Vol. 06, Issue 01, pp.&nbsp;139–144). https://jurnaljam.ub.ac.id/index.php/jam/article/view/1863</p>
<p>Indonesia Investments. (2024, January 7). Minyak Kelapa Sawit Indonesia - Produksi &amp; Ekspor CPO | Indonesia Investments. Indonesia-Investments.com. https://www.indonesia-investments.com/id/bisnis/komoditas/minyak-sawit/item166</p>
<p>Kementerian Pertanian Direktorat Jenderal Perkebunan : KONTRIBUSI MINYAK KELAPA SAWIT INDONESIA MENGATASI KRISIS PANGAN GLOBAL. (2022). Pertanian.go.id. https://ditjenbun.pertanian.go.id/kontribusi-minyak-kelapa-sawit-indonesia-mengatasi-krisis-pangan-global/</p>
<p>Kinski, N., Tanjung, A. A., &amp; Sukardi. (2023). Analisis Pengaruh Ekspor dan Impor Terhadap Pertumbuhan Ekonomi di Indonesia Tahun 2018 – 2. Ganaya : Jurnal Ilmu Sosial Dan Humaniora, 6(3), 568–578. https://doi.org/10.37329/ganaya.v6i3.2498</p>
<p>PT. Redbuzz Mediatama. (2017). Kelapa Sawit Indonesia Semakin Menjadi Andalan Ekonomi Nasional | Bina Sawit Makmur. Binasawitmakmur.com. https://binasawitmakmur.com/berita/kelapa-sawit-indonesia-semakin-menjadi-andalan-ekonomi-nasional</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>